# Business Problem

A hedge fund is seeking alternative asset classes to invest for its investors.  The hedge fund, which will remain anonymous, is already diversified across multiple asset classes - which includes equity, fixed incomes, real estate, and commodities.  The hedge fund has observed that retail and institutional investors have generated positive returns via cryptocurrency.  As a result, this hedge fund is requesting KBO Analytics to create a model that can predict Bitcoin prices in the future.

# Data Understanding

The data for examing the aforementioned problem comes from the following source: [Coin Codex](https://coincodex.com/crypto/bitcoin/historical-data/)

Before beginning to create any type of time series model, I want to examine and become familiar with the dataset. I will conduct exploratory data analysis in order to understand the dataset attributes, which includes, but not limited to the following:

1. Number of Columns
2. Number of Rows
3. Column Names
4. Format of the data in each column

In [2]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_pacf, plot_acf

import pmdarima as pm

In [3]:
# Reading File

bitcoin_df = pd.read_csv("data/bitcoin_2014_to_2026.csv")

In [4]:
# Examining the first 5 rows of the 'bitcoin_df' dataframe

bitcoin_df.head()

,Start,End,Open,High,Low,Close,Volume,Market Cap
0,2026-06-01,2026-06-02,73868.59,73986.02,70893.96,71439.79,3.773704e+10,1.450453e+12
1,2026-05-31,2026-06-01,73876.30,74271.63,73432.95,73688.05,2.145341e+10,1.480082e+12
2,2026-05-30,2026-05-31,73450.12,74080.02,73238.96,73867.98,3.748501e+10,1.477494e+12
3,2026-05-29,2026-05-30,73669.36,74323.98,72639.16,73476.46,4.408717e+10,1.474262e+12
4,2026-05-28,2026-05-29,74545.09,74573.73,72762.76,73553.92,5.189816e+10,1.472486e+12

In [5]:
# Examining the last 5 rows of the 'bitcoin_df' dataframe

bitcoin_df.tail()

,Start,End,Open,High,Low,Close,Volume,Market Cap
4526,2014-01-09,2014-01-10,841.47,864.36,804.14,846.86,5.177652e+07,1.030407e+10
4527,2014-01-08,2014-01-09,795.99,870.68,776.18,842.72,9.721611e+07,1.019892e+10
4528,2014-01-07,2014-01-08,946.49,965.74,802.00,802.00,7.558311e+07,1.104477e+10
4529,2014-01-06,2014-01-07,936.05,1017.12,905.71,953.29,8.422901e+07,1.174604e+10
4530,2014-01-05,2014-01-06,858.55,952.40,854.52,933.53,5.139392e+07,1.087804e+10

In [5]:
# Examining the shape of the 'bitcoin_df' dataframe

bitcoin_df.shape

(4531, 8)

In [7]:
# Examining the 'bitcoin_df' dataframe

bitcoin_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4531 entries, 0 to 4530
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Start       4531 non-null   object
 1   End         4531 non-null   object
 2   Open        4531 non-null   float64
 3   High        4531 non-null   float64
 4   Low         4531 non-null   float64
 5   Close       4531 non-null   float64
 6   Volume      4531 non-null   float64
 7   Market Cap  4531 non-null   float64
dtypes: float64(6), object(2)
memory usage: 283.3+ KB

In [6]:
# Obtaining descriptive analytics of the 'bitcoin_df' dataframe

bitcoin_df.describe()

,Open,High,Low,Close,Volume,Market Cap
count,4531.000000,4531.000000,4531.000000,4531.000000,4.531000e+03,4.531000e+03
mean,27003.688488,27526.497384,26456.890629,27021.663436,3.521488e+10,5.232794e+11
std,32160.258870,32680.823086,31612.563903,32168.110924,3.886304e+10,6.392699e+11
min,178.103000,211.731000,171.510000,178.795000,2.688736e+06,2.690697e+09
25%,1012.590000,1043.855000,991.586500,1016.730000,2.049405e+08,1.651487e+10
50%,10300.390061,10474.365680,10008.252865,10313.443526,2.374011e+10,1.832743e+11
75%,43288.930000,44145.078950,42490.183960,43326.830000,5.926236e+10,8.370000e+11
max,124696.000000,126025.000000,123164.000000,124735.000000,2.121958e+11,2.479741e+12

In [8]:
# Examining whether or not there is missing data

bitcoin_df.isna().sum()

Start         0
End           0
Open          0
High          0
Low           0
Close         0
Volume        0
Market Cap    0
dtype: int64

In [9]:
# Examining whether or not there are duplicates

bitcoin_df.duplicated().sum()

0

# Data Preparation

# Modeling

# Overall Conclusion and Recommendations

## Overall Conclusion and Recommendations

## Next Steps